/* Generated by Yosys 0.55+144 (git sha1 6440499e5, clang++ 18.1.3 -fPIC -O3) */

module sta_1(clk, in, out);
  input clk;
  wire clk;
  input in;
  wire in;
  wire launch_ff_D;
  wire launch_to_capture;
  output out;
  wire out;
  sky130_fd_sc_hs__dfxtp_1 _0_ (
    .CLK(clk),
    .D(launch_to_capture),
    .Q(out)
  );
  sky130_fd_sc_hs__dfxtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(launch_ff_D)
  );
  sky130_fd_sc_hs__buf_2 u_buf (
    .A(launch_ff_D),
    .X(launch_to_capture)
  );
endmodule
