/* Generated by Yosys 0.55+144 (git sha1 6440499e5, clang++ 18.1.3 -fPIC -O3) */

module sta_1(clk, in, out);
  wire _0_;
  wire _1_;
  input clk;
  wire clk;
  input in;
  wire in;
  wire launch_ff_D;
  wire launch_to_capture;
  output out;
  wire out;
  DFF_X1 _2_ (
    .CK(clk),
    .D(launch_to_capture),
    .Q(out),
    .QN(_1_)
  );
  DFF_X1 _3_ (
    .CK(clk),
    .D(in),
    .Q(launch_ff_D),
    .QN(_0_)
  );
  BUF_X2 u_buf (
    .A(launch_ff_D),
    .Z(launch_to_capture)
  );
endmodule
